export const ProblemPlatforms = {
  GFG: "Geeks for Geeks",
  LEETCODE: "LeetCode",
  CODEFORCES: "CodeForces",
  HACKERRANK: "HackerRank",
  CODECHEF: "CodeChef",
  INTERVIEWBIT: "InterviewBit",
  ATCODER: "AtCoder",
};

export const ProblemLevel = {
  EASY: "Easy",
  MEDIUM: "Medium",
  HARD: "Hard",
};

export const ProblemStatus = {
  SOLVED: "Solved",
  UNSOLVED: "Unsolved",
};

export const ProblemTags = {
  AD_HOC: "Ad-hoc",
  ALGORITHMS: "Algorithms",
  ARRAY: "Array",
  AVL_TREE: "AVL Tree",
  BACKTRACKING: "Backtracking",
  BELLMAN_FORD: "Bellman-Ford Algorithm",
  BFS: "Breadth First Search",
  BINARY_EXPONENTIATION: "Binary Exponentiation",
  BINARY_LIFTING: "Binary Lifting",
  BINARY_SEARCH: "Binary Search",
  BINARY_SEARCH_TREE: "Binary Search Tree",
  BINARY_TREE: "Binary Tree",
  BIT_MAGIC: "Bit Magic",
  BIT_MANIPULATION: "Bit Manipulation",
  BITMASK: "Bitmask",
  BRUTE_FORCE: "Brute Force",
  COMBINATORICS: "Combinatorics",
  CONVEX_HULL: "Convex Hull",
  DATA_STRUCTURES: "Data Structures",
  DEQUE: "Deque",
  DFS: "Depth First Search",
  DIJKSTRA: "Dijkstra's Algorithm",
  DISJOINT_SET: "Disjoint Set",
  DIVIDE_AND_CONQUER: "Divide and Conquer",
  DSA: "DSA",
  DYNAMIC_PROGRAMMING: "Dynamic Programming",
  DYNAMIC_TABLES: "Dynamic Tables",
  DSU: "Disjoint Set Union",
  EULER_PATH: "Euler Path",
  FENWICK_TREE: "Fenwick Tree",
  FLOYD_WARSHALL: "Floyd-Warshall Algorithm",
  GAME_THEORY: "Game Theory",
  GCD: "Greatest Common Divisor",
  GEOMETRY: "Geometry",
  GRAPH: "Graph",
  GREEDY: "Greedy",
  HASH_MAP: "Hash Map",
  HASH_TABLE: "Hash Table",
  HEAP: "Heap",
  HUFFMAN_CODING: "Huffman Coding",
  IMPLEMENTATION: "Implementation",
  INORDER_TRAVERSAL: "Inorder Traversal",
  KMP: "Knuth-Morris-Pratt",
  LCM: "Least Common Multiple",
  LCS: "Longest Common Subsequence",
  LINKED_LIST: "Linked List",
  LINE_SWEEP: "Line Sweep",
  LR_DP: "LR Dynamic Programming",
  MANACHER: "Manacher's Algorithm",
  MAP: "Map",
  MATRIX: "Matrix",
  MATRIX_EXPONENTIATION: "Matrix Exponentiation",
  MAXIMUM_FLOW: "Maximum Flow",
  MERGE_SORT: "Merge Sort",
  MIN_CUT: "Min Cut",
  MINIMUM_SPANNING_TREE: "Minimum Spanning Tree",
  MCM: "Matrix Chain Multiplication",
  MODULAR_ARITHMETIC: "Modular Arithmetic",
  MULTISET: "Multiset",
  NETWORK_FLOW: "Network Flow",
  NUMBER_THEORY: "Number Theory",
  OBSERVATION: "Observation",
  OPTIMISATION: "Optimisation",
  PALINDROMES: "Palindromes",
  PATTERN_FINDING: "Pattern Finding",
  PREFIX: "Prefix",
  PREFIX_SUM: "Prefix Sum",
  PRIORITY_QUEUE: "Priority Queue",
  PROBABILITY: "Probability",
  QUEUE: "Queue",
  RABIN_KARP: "Rabin-Karp",
  RANDOMIZED_ALGORITHMS: "Randomized Algorithms",
  RECURSION: "Recursion",
  SEARCHING: "Searching",
  SEGMENT_TREE: "Segment Tree",
  SET: "Set",
  SHORTEST_PATH: "Shortest Path",
  SIMULATION: "Simulation",
  SLIDING_WINDOW: "Sliding Window",
  SORTING: "Sorting",
  STACK: "Stack",
  STRING: "String",
  SUFFIX: "Suffix",
  SUFFIX_SUM: "Suffix Sum",
  TOPOLOGICAL_SORT: "Topological Sort",
  TRIE: "Trie",
  TREE: "Tree",
  TREE_DP: "Tree Dynamic Programming",
  TWO_POINTERS: "Two Pointers",
  UNION_FIND: "Union-Find",
  WEIGHT_GRAPH: "Weighted Graph",
  Z_ALGORITHM: "Z Algorithm",
};
