export const ProblemPlatforms = {
  GFG: "Geeks for Geeks",
  LEETCODE: "LeetCode",
  CODEFORCES: "CodeForces",
  HACKERRANK: "HackerRank",
  CODECHEF: "CodeChef",
  INTERVIEWBIT: "InterviewBit",
  ATCODER: "AtCoder",
};

export const ProblemLevel = {
  EASY: "Easy",
  MEDIUM: "Medium",
  HARD: "Hard",
};

export const ProblemStatus = {
  SOLVED: "Solved",
  UNSOLVED: "Unsolved",
};

export const ProblemTags = {
  ALGORITHMS: "Algorithms",
  ARRAY: "Array",
  AVL_TREE: "AVL Tree",
  BACKTRACKING: "Backtracking",
  BELLMAN_FORD: "Bellman-Ford Algorithm",
  BINARY_SEARCH: "Binary Search",
  BINARY_SEARCH_TREE: "Binary Search Tree",
  BINARY_TREE: "Binary Tree",
  BIT_MANIPULATION: "Bit Manipulation",
  BITS: "Bits",
  BRUTE_FORCE: "Brute Force",
  BFS: "Breadth First Search",
  COMBINATORICS: "Combinatorics",
  CONVEX_HULL: "Convex Hull",
  DATA_STRUCTURES: "Data Structures",
  DEQUE: "Deque",
  DFS: "Depth First Search",
  DIJKSTRA: "Dijkstra's Algorithm",
  DIVIDE_AND_CONQUER: "Divide and Conquer",
  DP: "Dynamic Programming",
  DSA: "DSA",
  DYNAMIC_TABLES: "Dynamic Tables",
  FENWICK_TREE: "Fenwick Tree",
  FLOYD_WARSHALL: "Floyd-Warshall Algorithm",
  GAME_THEORY: "Game Theory",
  GCD: "Greatest Common Divisor",
  GEOMETRY: "Geometry",
  GRAPH: "Graph",
  GREEDY: "Greedy",
  HASH_TABLE: "Hash Table",
  HEAP: "Heap",
  HUFFMAN_CODING: "Huffman Coding",
  IMPLEMENTATION: "Implementation",
  INORDER_TRAVERSAL: "Inorder Traversal",
  KMP: "Knuth-Morris-Pratt",
  LCM: "Least Common Multiple",
  LINE_SWEEP: "Line Sweep",
  LINKED_LIST: "Linked List",
  MANACHER: "Manacher's Algorithm",
  MATRIX_EXPONENTIATION: "Matrix Exponentiation",
  MAXIMUM_FLOW: "Maximum Flow",
  MIN_CUT: "Min Cut",
  MINIMUM_SPANNING_TREE: "Minimum Spanning Tree",
  MODULAR_ARITHMETIC: "Modular Arithmetic",
  NETWORK_FLOW: "Network Flow",
  NUMBER_THEORY: "Number Theory",
  POSTORDER_TRAVERSAL: "Postorder Traversal",
  PREFIX_SUM: "Prefix Sum",
  PRIME_FACTORIZATION: "Prime Factorization",
  PROBABILITY: "Probability",
  QUEUE: "Queue",
  RABIN_KARP: "Rabin-Karp",
  RANDOMIZED_ALGORITHMS: "Randomized Algorithms",
  RECURSION: "Recursion",
  SEARCHING: "Searching",
  SEGMENT_TREE: "Segment Tree",
  SHORTEST_PATH: "Shortest Path",
  SIMULATION: "Simulation",
  SLIDING_WINDOW: "Sliding Window",
  SORTING: "Sorting",
  STACK: "Stack",
  STRING: "String",
  SUFFIX_SUM: "Suffix Sum",
  TOPOLOGICAL_SORT: "Topological Sort",
  TRIE: "Trie",
  TREE: "Tree",
  TWO_POINTERS: "Two Pointers",
  UNION_FIND: "Union-Find",
  Z_ALGORITHM: "Z Algorithm",
};
